# Criação dos subgrupos

## Carregando os dados

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

In [3]:

df_estados = pd.read_csv(
    '/content/estados_id.csv',
)

In [4]:
df_municipios = pd.read_csv(
    '/content/municipios_id.csv',
)

In [5]:
df_municipios_com_estado = pd.merge(df_estados[['estado_id',	'uf']], df_municipios, on='estado_id', how='inner')

In [6]:
votacao_candidato = pd.read_csv(
    '/content/votacao_candidato.csv',
 encoding='latin1',
    sep=';')

In [7]:
votacao_senador = votacao_candidato[votacao_candidato['Cargo'] == 'Senador']

In [8]:
votacao_senador

,Ano de eleição,Cargo,Código município,Cor/raça,Estado civil,Faixa etária,Gênero,Grau de instrução,Município,Nome candidato,...,Ocupação,Partido,Região,Situação totalização,Turno,UF,Zona,Votos válidos,Votos nominais,Data de carga
106,2022,Senador,87734,Preta,Solteiro(a),40 a 44 anos,Feminino,Superior completo,OSÓRIO,SANDRA FIGUEIREDO,...,Vendedor de Comércio Varejista e Atacadista,PSB,SUL,Não Eleito,1,RS,77,24974,89,2026-05-09 03:30:52
592,2022,Senador,25038,Branca,Solteiro(a),55 a 59 anos,Feminino,Superior completo,PANELAS,ROBERTA RITA CAVALCANTI PEREIRA,...,Advogado,PCO,NORDESTE,Não Eleito,1,PE,47,12648,0,2026-05-09 03:30:52
594,2022,Senador,24899,Parda,Solteiro(a),35 a 39 anos,Feminino,Superior completo,NAZARÉ DA MATA,MARIA EUGENIA WANDERLEY LIMA,...,Ocupante de Cargo em Comissão,PSOL,NORDESTE,Não Eleito,1,PE,23,15404,81,2026-05-09 03:30:52
595,2022,Senador,23183,Parda,Solteiro(a),35 a 39 anos,Feminino,Superior completo,LAGOA GRANDE,MARIA EUGENIA WANDERLEY LIMA,...,Ocupante de Cargo em Comissão,PSOL,NORDESTE,Não Eleito,1,PE,137,13553,14,2026-05-09 03:30:52
664,2022,Senador,25216,Branca,Solteiro(a),55 a 59 anos,Feminino,Superior completo,PETROLINA,ROBERTA RITA CAVALCANTI PEREIRA,...,Advogado,PCO,NORDESTE,Não Eleito,1,PE,83,52718,0,2026-05-09 03:30:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9376441,2022,Senador,58408,Branca,Solteiro(a),65 a 69 anos,Masculino,Superior completo,ARMAÇÃO DOS BÚZIOS,ANTONIO HERMANO LEMME,...,Aposentado (Exceto Servidor Público),PCO,SUDESTE,Não Eleito,1,RJ,172,17654,0,2026-05-09 03:30:52
9376444,2022,Senador,58335,Branca,Solteiro(a),65 a 69 anos,Masculino,Superior completo,DUQUE DE CAXIAS,ANTONIO HERMANO LEMME,...,Aposentado (Exceto Servidor Público),PCO,SUDESTE,Não Eleito,1,RJ,79,54281,0,2026-05-09 03:30:52
9376837,2022,Senador,70297,Branca,Divorciado(a),45 a 49 anos,Masculino,Superior completo,SANTA CRUZ DO RIO PARDO,TITO FLAVIO BELLINI NOGUEIRA DE OLIVEIRA,...,Professor de Ensino Superior,PCB,SUDESTE,Não Eleito,1,SP,114,22312,34,2026-05-09 03:30:52
9376933,2022,Senador,25313,Branca,Casado(a),60 a 64 anos,Masculino,Superior completo,RECIFE,ANDRÉ CARLOS ALVES DE PAULA FILHO,...,Deputado,PSD,NORDESTE,Não Eleito,1,PE,6,71781,3464,2026-05-09 03:30:52
9376944,2022,Senador,86304,Branca,Divorciado(a),55 a 59 anos,Feminino,Ensino Fundamental completo,AMETISTA DO SUL,MARISTELA ZANOTTO,...,Empresário,PSC,SUL,Não Eleito,1,RS,64,4222,4,2026-05-09 03:30:52

In [9]:
votacao_senador_agrupado = (
    votacao_senador.groupby(
        ["Código município", "Partido", "Turno"],
        as_index=False
    )
    .agg({
        # "Cargo": "first",
        # "Cor/raça": "first",
         "Município": "first",
        # "Estado civil": "first",
        # "Faixa etária": "first",
        # "Gênero": "first",
        # "Grau de instrução": "first",
        # "Ocupação": "first",
       # "Partido": "first",
        #"Situação totalização": "first",
        "UF": "first",
        "Votos nominais": "sum"
    })
)

In [10]:
votacao_senador_agrupado

       Código município   Partido  Turno      Município  UF  Votos nominais
0                    19      AGIR      1  GUAJARÁ-MIRIM  RO              57
1                    19       PDT      1  GUAJARÁ-MIRIM  RO               0
2                    19        PL      1  GUAJARÁ-MIRIM  RO            5624
3                    19       PMB      1  GUAJARÁ-MIRIM  RO              84
4                    19        PP      1  GUAJARÁ-MIRIM  RO             786
...                 ...       ...    ...            ...  ..             ...
45554             99074      NOVO      1       INDIAVAÍ  MT               3
45555             99074  PATRIOTA      1       INDIAVAÍ  MT              35
45556             99074        PL      1       INDIAVAÍ  MT             812
45557             99074      PSOL      1       INDIAVAÍ  MT               6
45558             99074       PTB      1       INDIAVAÍ  MT             204

[45559 rows x 6 columns]

In [11]:
votacao_partidos_maiores = votacao_senador_agrupado.loc[
    votacao_senador_agrupado.groupby('Código município')['Votos nominais'].idxmax()
]

In [12]:
votacao_partidos_maiores

,Código município,Partido,Turno,Município,UF,Votos nominais
6,19,REPUBLICANOS,1,GUAJARÁ-MIRIM,RO,7876
13,35,REPUBLICANOS,1,PORTO VELHO,RO,97329
16,51,PL,1,JI-PARANÁ,RO,25652
23,78,PL,1,ARIQUEMES,RO,22624
32,94,PP,1,CACOAL,RO,16298
...,...,...,...,...,...,...
45532,98990,PL,1,VILA RICA,MT,4524
45538,99015,PL,1,COMODORO,MT,4656
45544,99031,PL,1,FIGUEIRÓPOLIS D'OESTE,MT,952
45550,99058,PL,1,GUARANTÃ DO NORTE,MT,6836
45556,99074,PL,1,INDIAVAÍ,MT,812

In [13]:
import unicodedata
import re

def transformar_nome_cidade(texto):

    texto_sem_acentos = unicodedata.normalize(
        'NFKD',
        str(texto)
    ).encode(
        'ASCII',
        'ignore'
    ).decode('ASCII')

    # remove apostrofos
    texto_sem_acentos = texto_sem_acentos.replace("'", "")

    # troca espaços por hífen
    resultado = texto_sem_acentos.replace(" ", "-")

    # remove caracteres especiais restantes
    resultado = re.sub(r'[^a-zA-Z0-9\-]', '', resultado)

    return resultado.lower().strip()

In [14]:
df_panorama = pd.read_csv('/content/drive/MyDrive/9 período/descritiva/dados_municipios_panorama.csv')

In [15]:
votacao_partidos_maiores['Município'] = votacao_partidos_maiores['Município'].apply(transformar_nome_cidade)
df_panorama['municipio'] = df_panorama['municipio'].apply(transformar_nome_cidade)
df_municipios_com_estado['nome'] = df_municipios_com_estado['nome'].apply(transformar_nome_cidade)

In [16]:
votacao_senador_maiores_com_municipio = pd.merge(df_municipios_com_estado, votacao_partidos_maiores, left_on=['nome', 'uf'], right_on=['Município', 'UF'], how='inner')

In [17]:
df_senadores = pd.merge(
    votacao_senador_maiores_com_municipio,
    df_panorama,
    on='municipio_id',
    how='inner'
)

In [18]:
df_senadores

,estado_id,uf,municipio_id,nome,Código município,Partido,Turno,Município,UF,Votos nominais,...,População exposta ao risco,Bioma predominante,Sistema Costeiro-Marinho,Área da unidade territorial,Hierarquia urbana,Região de Influência,Região intermediária,Região imediata,Mesorregião,Microrregião
0,11,RO,1100015,alta-floresta-doeste,310,PP,1,alta-floresta-doeste,RO,4833,...,Sem dados,Amazônia,Não pertence,"7.067,127",Centro Local (5),Cacoal - Capital Regional C (2C),Ji-Paraná,Cacoal,Leste Rondoniense,Cacoal
1,11,RO,1100379,alto-alegre-dos-parecis,736,REPUBLICANOS,1,alto-alegre-dos-parecis,RO,2221,...,Sem dados,Amazônia,Não pertence,"3.958,273",Centro Local (5),Rolim de Moura - Centro Subregional B...,Ji-Paraná,Cacoal,Leste Rondoniense,Cacoal
2,11,RO,1100403,alto-paraiso,639,PL,1,alto-paraiso,RO,3347,...,Sem dados,Amazônia,Não pertence,"2.652,03",Centro Local (5),Ariquemes - Centro Subregional A (3A),Porto Velho,Ariquemes,Leste Rondoniense,Ariquemes
3,11,RO,1100023,ariquemes,78,PL,1,ariquemes,RO,22624,...,Sem dados,Amazônia,Não pertence,"4.426,127",Centro Subregional A (3A),Arranjo Populacional de Porto Velho/R...,Porto Velho,Ariquemes,Leste Rondoniense,Ariquemes
4,11,RO,1100452,buritis,779,PL,1,buritis,RO,6157,...,Sem dados,Amazônia,Não pertence,"3.265,811",Centro Local (5),Ariquemes - Centro Subregional A (3A),Porto Velho,Ariquemes,Madeira-Guaporé,Porto Velho
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5551,52,GO,5222005,vianopolis,96415,UNIÃO,1,vianopolis,GO,2010,...,Sem dados,Cerrado,Não pertence,"954,115",Centro Local (5),Arranjo Populacional de Goiânia/GO - ...,Goiânia,Anápolis,Sul Goiano,Pires do Rio
5552,52,GO,5222054,vicentinopolis,96571,PSDB,1,vicentinopolis,GO,1802,...,Sem dados,Cerrado,Não pertence,"733,794",Centro Local (5),Arranjo Populacional de Goiânia/GO - ...,Itumbiara,Piracanjuba,Sul Goiano,Meia Ponte
5553,52,GO,5222203,vila-boa,93289,PSDB,1,vila-boa,GO,798,...,Sem dados,Cerrado,Não pertence,"1.052,593",Centro Local (5),Formosa - Centro Subregional B (3B),Luziânia - Águas Lindas de Goiás,Flores de Goiás,Leste Goiano,Entorno de Brasília
5554,52,GO,5222302,vila-propicio,93505,UNIÃO,1,vila-propicio,GO,1630,...,Sem dados,Cerrado,Não pertence,"2.181,593",Centro Local (5),Arranjo Populacional de Goianésia/GO ...,Porangatu - Uruaçu,Ceres - Rialma - Goianésia,Leste Goiano,Entorno de Brasília
5555,53,DF,5300108,brasilia,97012,REPUBLICANOS,1,brasilia,DF,714562,...,Sem dados,Cerrado,Não pertence,"5.760,785",Metrópole Nacional (1B) - Município i...,Arranjo Populacional de Brasília/DF -...,Distrito Federal,Distrito Federal,Distrito Federal,Brasília

## Tratando os dados

In [19]:
def turn_value_to_international_stardand(value):
  if isinstance(value, int):
    return value
  if isinstance(value, float):
    return value

  valor = value.replace(".", "")
  valor = valor.replace(",", ".")

  return float(valor)

def categorizar_valores(valores):
  try:
    return pd.qcut(
      valores,
      q=3,
      labels=["valor_baixo", "valor_medio", "valor_alto"],
  ).tolist()
  except:
     return pd.cut(
      valores,
       bins=3,
      labels=["valor_baixo", "valor_medio", "valor_alto"],
  ).tolist()

In [20]:
def remove_barra(value):
  return 0 if value == '-' else value

In [21]:
colunas_numericas = [
    "População no último censo",
    "População quilombola",
    "População indígena",
    "Densidade demográfica",
    "Salário médio mensal dos trabalhadores formais",
    "Pessoal ocupado em postos de trabalho formais",
    "Percentual da população com rendimento nominal mensal per capita de até 1/2 salário mínimo",
    "Taxa de escolarização de 6 a 14 anos de idade",
    "IDEB – Anos iniciais do ensino fundamental (Rede pública)",
    "IDEB – Anos finais do ensino fundamental (Rede pública)",
    "Matrículas no ensino fundamental",
    "Matrículas no ensino médio",
    "Docentes no ensino fundamental",
    "Docentes no ensino médio",
    "Número de estabelecimentos de ensino fundamental",
    "Número de estabelecimentos de ensino médio",
    "PIB per capita",
    "Índice de Desenvolvimento Humano Municipal (IDHM)",
    "Total de receitas brutas realizadas",
    "Transferências correntes (Percentual em relação às receitas correntes brutas realizadas)",
    "Total de despesas brutas empenhadas",
    "Mortalidade Infantil",
    "Internações por diarreia pelo SUS",
    "Estabelecimentos de Saúde SUS",
    "Área urbanizada",
    "Esgotamento sanitário por rede geral, rede pluvial ou fossa ligada à rede",
    "Arborização de vias públicas",
    "Urbanização de vias públicas",
    "Área da unidade territorial"
]

In [22]:
for coluna in colunas_numericas:
  if len(df_senadores[df_senadores[coluna] == 'Sem dados']) > 0:
    df_senadores = df_senadores.drop(columns=[coluna])
    continue

  df_senadores.loc[:, coluna] = (
      df_senadores[coluna]
      .apply(remove_barra)
  )
  df_senadores.loc[:, coluna] = (
      df_senadores[coluna]
      .apply(turn_value_to_international_stardand)
  )

In [23]:
colunas_per_capita = [
    "População quilombola",
    "População indígena",
    "Pessoal ocupado em postos de trabalho formais",
    "Matrículas no ensino fundamental",
    "Matrículas no ensino médio",
    "Docentes no ensino fundamental",
    "Docentes no ensino médio",
    "Número de estabelecimentos de ensino fundamental",
    "Número de estabelecimentos de ensino médio",
    "Estabelecimentos de Saúde SUS"
]

pop_col = "População no último censo"

for coluna in colunas_per_capita:
    df_senadores[coluna] = (
        df_senadores[coluna].astype(float)
        / df_senadores[pop_col].astype(float)
    )

In [24]:
df_senadores['Área urbanizada']  = df_senadores['Área urbanizada'].astype(float) /df_senadores['Área da unidade territorial'].astype(float)

In [25]:
%%capture
for coluna in colunas_numericas:
  df_senadores.loc[:, coluna] = categorizar_valores(list(df_senadores[coluna]))

In [26]:
df_senadores['Partido'].unique()

array(['PP', 'REPUBLICANOS', 'PL', 'UNIÃO', 'PSB', 'PODE', 'PROS', 'PSD',
       'PDT', 'PSOL', 'PT', 'PSDB', 'PRTB', 'MDB', 'PTB', 'PSC', 'PV'],
      dtype=object)

In [27]:
df_senadores.groupby('Partido').size().sort_values(ascending=False)

Partido
PL              1455
PSD              857
PT               765
PP               443
UNIÃO            441
PSB              423
PSC              368
REPUBLICANOS     328
MDB              168
PODE             143
PSDB              82
PTB               32
PDT               26
PROS              16
PV                 5
PRTB               3
PSOL               1
dtype: int64

In [29]:
colunas_nao_contar =[
    "estado_id",
    "uf",
    "municipio_id",
    "nome",
    "Código município",
    "Partido",
    "Situação totalização",
    "Turno",
    "UF",
    "Votos nominais",
    "municipio",
    "População no último censo",
    "População estimada",
    # "População quilombola",
    # "População indígena",
    # "Densidade demográfica",
    "Nome masculino mais popular",
    "Nome feminino mais popular",
    "Sobrenome mais popular",
    # "Salário médio mensal dos trabalhadores formais",
    # "Pessoal ocupado em postos de trabalho formais",
    # "Percentual da população com rendimento nominal mensal per capita de até 1/2 salário mínimo",
    # "Taxa de escolarização de 6 a 14 anos de idade",
    # "IDEB – Anos iniciais do ensino fundamental (Rede pública)",
    # "IDEB – Anos finais do ensino fundamental (Rede pública)",
     "Matrículas no ensino fundamental",
    "Matrículas no ensino médio",
    "Docentes no ensino fundamental",
    "Docentes no ensino médio",
    "Número de estabelecimentos de ensino fundamental",
    "Número de estabelecimentos de ensino médio",
    # "PIB per capita",
    # "Índice de Desenvolvimento Humano Municipal (IDHM)",
    "Total de receitas brutas realizadas",
    "Transferências correntes (Percentual em relação às receitas correntes brutas realizadas)",
    "Total de despesas brutas empenhadas",
    # "Mortalidade Infantil",
    # "Internações por diarreia pelo SUS",
    # "Estabelecimentos de Saúde SUS",
    # "Área urbanizada",
    # "Esgotamento sanitário por rede geral, rede pluvial ou fossa ligada à rede",
    # "Arborização de vias públicas",
    # "Urbanização de vias públicas",
    "População exposta ao risco",
    "Bioma predominante",
    "Sistema Costeiro-Marinho",
    "Área da unidade territorial",
    "Hierarquia urbana",
    "Região de Influência",
    "Região intermediária",
    "Região imediata",
    "Mesorregião",
    "Microrregião"
]

## Criando subgrupos

### PT

In [55]:
%%capture
!pip install pysubgroup

In [56]:
import pysubgroup as ps

target = ps.BinaryTarget(
    'Partido',
    'PT'
)

searchspace = ps.create_selectors(df_senadores, ignore=colunas_nao_contar)

task = ps.SubgroupDiscoveryTask(
    df_senadores,
    target,
    searchspace,
    result_set_size=20,
    depth=5,
    qf=ps.StandardQF(a=0.5),
    min_quality=0.01
)

result = ps.BeamSearch(beam_width=30).execute(task)

In [57]:
result.to_dataframe()[['subgroup', 'quality']]

                                             subgroup   quality
0   IDEB – Anos finais do ensino fundamental (Rede...  0.112990
1   IDEB – Anos finais do ensino fundamental (Rede...  0.112990
2   IDEB – Anos finais do ensino fundamental (Rede...  0.112660
3   IDEB – Anos finais do ensino fundamental (Rede...  0.112660
4   IDEB – Anos finais do ensino fundamental (Rede...  0.111292
5   IDEB – Anos finais do ensino fundamental (Rede...  0.111292
6   IDEB – Anos finais do ensino fundamental (Rede...  0.110892
7   IDEB – Anos finais do ensino fundamental (Rede...  0.110892
8   IDEB – Anos finais do ensino fundamental (Rede...  0.102913
9   IDEB – Anos finais do ensino fundamental (Rede...  0.102913
10  IDEB – Anos finais do ensino fundamental (Rede...  0.102483
11  IDEB – Anos finais do ensino fundamental (Rede...  0.102483
12  IDEB – Anos finais do ensino fundamental (Rede...  0.099876
13  IDEB – Anos finais do ensino fundamental (Rede...  0.099356
14  IDEB – Anos finais do ensino fundamental (Rede...  0.099356
15  IDEB – Anos finais do ensino fundamental (Rede...  0.099101
16  IDEB – Anos finais do ensino fundamental (Rede...  0.098912
17  IDEB – Anos finais do ensino fundamental (Rede...  0.098912
18  IDEB – Anos finais do ensino fundamental (Rede...  0.098627
19  IDEB – Anos finais do ensino fundamental (Rede...  0.098627

### PL

In [51]:
import pysubgroup as ps

target_2 = ps.BinaryTarget(
    'Partido',
    'PL'
)

searchspace_2 = ps.create_selectors(df_senadores, ignore=colunas_nao_contar)

task_2 = ps.SubgroupDiscoveryTask(
    df_senadores,
    target_2,
    searchspace_2,
    result_set_size=20,
    depth=5,
    qf=ps.StandardQF(a=0.5),
    min_quality=0.01
)

result_2 = ps.BeamSearch(beam_width=30).execute(task_2)

In [52]:
result_2.to_dataframe()[['subgroup', 'quality']]

                                             subgroup   quality
0   Arborização de vias públicas=='valor_alto' AND...  0.159550
1   Arborização de vias públicas=='valor_alto' AND...  0.159550
2   Arborização de vias públicas=='valor_alto' AND...  0.159550
3   Arborização de vias públicas=='valor_alto' AND...  0.159550
4   Arborização de vias públicas=='valor_alto' AND...  0.155594
5   Arborização de vias públicas=='valor_alto' AND...  0.155594
6   Arborização de vias públicas=='valor_alto' AND...  0.155594
7   Arborização de vias públicas=='valor_alto' AND...  0.152168
8   Arborização de vias públicas=='valor_alto' AND...  0.152168
9   Arborização de vias públicas=='valor_alto' AND...  0.152168
10  Arborização de vias públicas=='valor_alto' AND...  0.152168
11  Esgotamento sanitário por rede geral, rede plu...  0.150330
12  Esgotamento sanitário por rede geral, rede plu...  0.150330
13  Esgotamento sanitário por rede geral, rede plu...  0.150156
14  Esgotamento sanitário por rede geral, rede plu...  0.150156
15  Esgotamento sanitário por rede geral, rede plu...  0.147478
16  Esgotamento sanitário por rede geral, rede plu...  0.147478
17  Esgotamento sanitário por rede geral, rede plu...  0.147478
18  Esgotamento sanitário por rede geral, rede plu...  0.147478
19  Pessoal ocupado em postos de trabalho formais=...  0.145017

### PSD

In [53]:
import pysubgroup as ps

target_3 = ps.BinaryTarget(
    'Partido',
    'PSD'
)

searchspace_3 = ps.create_selectors(df_senadores, ignore=colunas_nao_contar)

task_3 = ps.SubgroupDiscoveryTask(
    df_senadores,
    target_3,
    searchspace_3,
    result_set_size=20,
    depth=5,
    qf=ps.StandardQF(a=0.5),
    min_quality=0.01
)

result_3 = ps.BeamSearch(beam_width=30).execute(task_3)

In [54]:
result_3.to_dataframe()[['subgroup', 'quality']]

                                             subgroup   quality
0   Internações por diarreia pelo SUS=='valor_baix...  0.122389
1   Internações por diarreia pelo SUS=='valor_baix...  0.122227
2   PIB per capita=='valor_baixo' AND Pessoal ocup...  0.122145
3   PIB per capita=='valor_baixo' AND Pessoal ocup...  0.121983
4   Internações por diarreia pelo SUS=='valor_baix...  0.115251
5   PIB per capita=='valor_baixo' AND Pessoal ocup...  0.114959
6   PIB per capita=='valor_baixo' AND Pessoal ocup...  0.114798
7   IDEB – Anos finais do ensino fundamental (Rede...  0.111314
8   IDEB – Anos finais do ensino fundamental (Rede...  0.110965
9   IDEB – Anos finais do ensino fundamental (Rede...  0.110965
10  PIB per capita=='valor_baixo' AND Pessoal ocup...  0.109325
11  Internações por diarreia pelo SUS=='valor_baix...  0.109257
12  Densidade demográfica=='valor_baixo' AND Inter...  0.108577
13  Densidade demográfica=='valor_baixo' AND Inter...  0.108453
14  PIB per capita=='valor_baixo' AND Pessoal ocup...  0.108350
15  Internações por diarreia pelo SUS=='valor_baix...  0.108281
16  Densidade demográfica=='valor_baixo' AND PIB p...  0.108280
17  Densidade demográfica=='valor_baixo' AND PIB p...  0.108174
18  Densidade demográfica=='valor_baixo' AND PIB p...  0.108104
19  Densidade demográfica=='valor_baixo' AND Inter...  0.107809